// <auto-generated />
namespace FTN.ESI.SIMES.CIM.CIMAdapter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class resourceId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resourceId));
        
        string IMigrationMetadata.Id
        {
            get { return "202110060911016_resourceId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
